package bg.com.bo.demoBG.dao;

import bg.com.bo.demoBG.domain.AchCamaras;
import bg.com.bo.demoBG.domain.AchCamarasExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AchCamarasMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@SelectProvider(type = AchCamarasSqlProvider.class, method = "countByExample")
	long countByExample(AchCamarasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@DeleteProvider(type = AchCamarasSqlProvider.class, method = "deleteByExample")
	int deleteByExample(AchCamarasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@Delete({ "delete from GANADERO.ACH_CAMARAS", "where CODIGO = #{codigo,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@Insert({ "insert into GANADERO.ACH_CAMARAS (CODIGO, DESCRIPCION, ", "TZ_LOCK)",
			"values (#{codigo,jdbcType=INTEGER}, #{descripcion,jdbcType=VARCHAR}, ", "#{tz_lock,jdbcType=VARCHAR})" })
	int insert(AchCamaras row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@InsertProvider(type = AchCamarasSqlProvider.class, method = "insertSelective")
	int insertSelective(AchCamaras row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@SelectProvider(type = AchCamarasSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "CODIGO", property = "codigo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TZ_LOCK", property = "tz_lock", jdbcType = JdbcType.VARCHAR) })
	List<AchCamaras> selectByExample(AchCamarasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@Select({ "select", "CODIGO, DESCRIPCION, TZ_LOCK", "from GANADERO.ACH_CAMARAS",
			"where CODIGO = #{codigo,jdbcType=INTEGER}" })
	@Results({ @Result(column = "CODIGO", property = "codigo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "DESCRIPCION", property = "descripcion", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TZ_LOCK", property = "tz_lock", jdbcType = JdbcType.VARCHAR) })
	AchCamaras selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@UpdateProvider(type = AchCamarasSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("row") AchCamaras row, @Param("example") AchCamarasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@UpdateProvider(type = AchCamarasSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("row") AchCamaras row, @Param("example") AchCamarasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@UpdateProvider(type = AchCamarasSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(AchCamaras row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GANADERO.ACH_CAMARAS
	 * @mbg.generated
	 */
	@Update({ "update GANADERO.ACH_CAMARAS", "set DESCRIPCION = #{descripcion,jdbcType=VARCHAR},",
			"TZ_LOCK = #{tz_lock,jdbcType=VARCHAR}", "where CODIGO = #{codigo,jdbcType=INTEGER}" })
	int updateByPrimaryKey(AchCamaras row);
}